wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - ${public_port}:80
  volumes:
    - ${wp_stack_name}_wp_vol:/var/www/html/wp-content
  volume_driver: convoy-efs
  labels:
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
