wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - ${public_port}:80
  volumes:
    - ${wp_stack_name}_wp_vol:/var/www/html/wp-content
  volume_driver: convoy-efs
  labels:
    io.rancher.container.pull_image: always
    rancher.lb.sync.register: true
    rancher.lb.sync.ext_port: ${lb_port}
    rancher.lb.sync.service_port: ${public_port}
    rancher.lb.sync.full_name: ${domain_names}
  tty: true
  stdin_open: true

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
